name: CD
on:
  push:
    branches: [prod]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Run tests
        run: pytest
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: devyanimahajan/mleng_sayhi:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_SERVER_IP }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull devyanimahajan/mleng_sayhi:latest
            docker run --rm -v /opt/assignment_outputs:/app/data devyanimahajan/mleng_sayhi:latest